version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
      - auth-service

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5050:5050"

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - backend